In [1]:
import pandas as pd
import numpy as np

In [2]:
tdsg = pd.read_csv('TDSG_024_2021_60min_nospec.csv', index_col=0, parse_dates=True, dayfirst=True)

In [6]:
#tdsg = pd.read_csv('TDSG_024_2021_60min_nospec.csv', index_col=0, parse_dates=True)    
h10 = tdsg[['GMfromSpectrum', 'MeteoRainfall']].fillna(0)

print("Liczba wszystkich wyników: ", h10['GMfromSpectrum'].count())
deszcz_idx = h10[h10['MeteoRainfall'] > 0].index
print("Liczba wyników z deszczem: ", len(deszcz_idx))
print("Liczba wyników bez deszczu: ", h10['GMfromSpectrum'].count() - len(deszcz_idx))

for i in deszcz_idx:
    #print(i)
    idx = pd.date_range(i - pd.Timedelta("1H"), i + pd.Timedelta("2H"), freq='H')
    #print(idx)
    #break
    h10.drop(idx, inplace=True, errors='ignore')
#h10.drop(idx, inplace=True, errors='ignore')

print("Liczba wyników do obliczeń: ", h10['GMfromSpectrum'].count())
#print(h10)

h10_mon = h10["GMfromSpectrum"].resample('M') #, closed='left')
#print(h10_mon)
h10_mon.agg([np.size, np.min, np.max, np.mean, np.std])
#h10_mon.sum()

Liczba wszystkich wyników:  8989
Liczba wyników z deszczem:  660
Liczba wyników bez deszczu:  8329
Liczba wyników do obliczeń:  7554

            size     amin     amax       mean       std
Date
2020-12-31   632  38.2509  54.4150  40.876736  1.716553
2021-01-31   606  37.4790  51.9017  39.392860  1.466751
2021-02-28   568  34.7390  48.0436  37.746886  1.903319
2021-03-31   646  38.2992  46.6045  39.027615  0.550531
2021-04-30   583  38.4823  44.0207  39.536413  0.716955
2021-05-31   537  34.9930  51.2003  40.024815  1.393686
2021-06-30   582  39.2459  43.3452  41.232435  0.798502
2021-07-31   680  39.1100  82.4424  41.557910  4.247363
2021-08-31   640  38.6508  79.8964  41.045310  4.498754
2021-09-30   639  38.6215  42.8289  40.153143  0.913728
2021-10-31   675  31.8418  44.3381  41.026532  0.933834
2021-11-30   552  38.8649  62.6301  40.629721  1.700344
2021-12-31   214  38.6069  62.7094  40.278543  3.212544